# Generated by Django 2.0 on 2020-05-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RetrievalCore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='feature_vector',
        ),
    ]
