"""
Django settings for MultiTopicDocRetrieval project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys
import pymysql

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# 令django识别apps/目录
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-)od70sl_ceuco35r%(+m2^3g7lrfl51&-zh1)(*0vo#)7xdr%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'Prepare',
    'RetrievalCore',

    'xadmin',
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MultiTopicDocRetrieval.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MultiTopicDocRetrieval.wsgi.application'

AUTH_USER_MODEL = 'RetrievalCore.UserProfile'

pymysql.install_as_MySQLdb()
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'DocRetrieval',
        'USER': 'root',
        'PASSWORD': 'Doc123456',
        'HOST': 'rm-bp1uk5g6qxw3mqpeevo.mysql.rds.aliyuncs.com',
        # 'OPTIONS': {
        #     "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        # }
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


STATIC_URL = '/static/'

STATICFILES_DIRS = (
    # Linux以及Mac系统下、此处需要指定本地路径的具体位置,部署上线时需要注意
    # r'C:/Users/Mr.Robot/Desktop/workspace/SmartDocRetrieval/static/',
    os.path.join(BASE_DIR, "static"),
    # os.path.join(BASE_DIR, "/static/css/"),
)

# 推荐算法相关参数
CLASS_NUM = [5, 5, 5]
SESSION_NUM = [300, 150, 300]
ETA = 0.5
classification = [[{"category_name": 'pregnancy and ert', "category_code": 0},
                   {"category_name": 'dysmenorrhea and menstruation', "category_code": 1},
                   {"category_name": 'sterilization and delivery', "category_code": 2},
                   {"category_name": 'preterm labor and ectopic pregnancy', "category_code": 3},
                   {"category_name": 'menopause and premature menopause', "category_code": 4}],
                  [{"category_name": 'std and sex', "category_code": 0},
                   {"category_name": 'prostate cancer and sex', "category_code": 1},
                   {"category_name": 'infertility and fertility', "category_code": 2},
                   {"category_name": 'vasectomy and family planning', "category_code": 3},
                   {"category_name": 'semen and infertility', "category_code": 4}],
                  [{"category_name": 'stroke and cataract', "category_code": 0},
                   {"category_name": 'mci and dementia', "category_code": 1},
                   {"category_name": 'tremor and essential tremor', "category_code": 2},
                   {"category_name": 'menopause and premature menopause', "category_code": 3},
                   {"category_name": 'prostate cancer and incontinence', "category_code": 4}]
                  ]


Superuser = {
    "account": "NJUST",
    "password": "admin1234"
}


